from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

REQUIRED = [
    "README.md",
    "ARCHITECTURE.md",
    "docs/SPEC.md",
    "docs/DOMAIN.md",
    "docs/BUSINESS_RULES.md",
    "docs/DOCX_MAPPING.md",
    "docs/API.md",
    "docs/TESTING.md",
    "docs/DOCX_TEMPLATE_INVENTORY.md",
    "docs/DOCX_TABLE_INVENTORY.md",
    "docs/PHASE10_E2E_REPORT.md",
    "golden/golden_comparison.md",
    "docker-compose.yml",
    ".env.example",
    "backend/app/main.py",
    "backend/requirements.txt",
    "backend/alembic/versions/0001_initial.py",
    "backend/alembic/versions/0002_phase1_domain.py",
    "backend/alembic/versions/0003_phase2_engines.py",
    "backend/alembic/versions/0004_phase3_pk_sampling.py",
    "backend/alembic/versions/0005_phase4_statistics.py",
    "backend/alembic/versions/0006_phase5_validation_evidence.py",
    "backend/alembic/versions/0007_phase6_research_ingest.py",
    "backend/alembic/versions/0008_phase7_local_ai.py",
    "backend/alembic/versions/0009_phase8_protocol_assembly.py",
    "backend/alembic/versions/0010_phase9_docx.py",
    "backend/app/services/project_service.py",
    "backend/app/services/study_engine_service.py",
    "backend/app/services/pk_engine_service.py",
    "backend/app/services/statistics_service.py",
    "backend/app/services/validation_service.py",
    "backend/app/services/research_service.py",
    "backend/app/services/research_engine_service.py",
    "backend/app/services/document_service.py",
    "backend/app/services/ai_extraction_service.py",
    "backend/app/services/protocol_service.py",
    "backend/app/services/docx_service.py",
    "backend/app/domain/design_validation.py",
    "backend/app/domain/sampling.py",
    "backend/app/domain/sample_size.py",
    "backend/app/domain/cv_pooling.py",
    "backend/app/domain/validation_engine.py",
    "backend/app/domain/study_snapshot.py",
    "backend/app/domain/document_ingest.py",
    "backend/app/domain/research_profile.py",
    "backend/app/domain/ai_provider.py",
    "backend/app/domain/ai_prompts.py",
    "backend/app/domain/ai_schemas.py",
    "backend/app/domain/protocol_assembly.py",
    "backend/app/domain/protocol_sections.py",
    "backend/app/domain/docx_renderer.py",
    "backend/app/domain/docx_profile.py",
    "frontend/package.json",
    "frontend/src/App.tsx",
    "schemas/BE_Protocol_Study_Schema_v1.json",
    "templates/protocol/BE_Protocol_Template_v2.0.docx",
]


def test_phase0_required_artifacts_exist() -> None:
    missing = [rel for rel in REQUIRED if not (ROOT / rel).exists()]
    assert missing == [], f"Missing Phase 0 artifacts: {missing}"
