"""Named constants and design/food rule parameters.

Numeric structural constraints live here — never hard-code in React.
"""

SCHEMA_VERSION = "1"
RULES_CATALOG_VERSION = "1"
PK_PARAMETER_CODES = (
    "Cmax",
    "Tmax",
    "AUC0_t",
    "AUC0_inf",
    "Kel",
    "T1_2",
    "AUCextr",
)
ANALYTE_TYPES = ("PARENT", "ACTIVE_METABOLITE", "INACTIVE_METABOLITE", "OTHER")

DEFAULT_STUDY_PHASE = "bioequivalence"
DEFAULT_PROJECT_STATUS = "draft"
DEFAULT_STUDY_STATUS = "draft"
DEFAULT_ENTITY_STATUS = "MISSING"
DEFAULT_ORIGIN = "USER"
DEFAULT_DECISION_STATUS = "PROPOSED"

# Design structural rules (versioned rule catalog placeholders)
CROSSOVER_2X2_REQUIRED_PERIODS = 2
CROSSOVER_2X2_REQUIRED_SEQUENCE_COUNT = 2
PARALLEL_REQUIRED_PERIODS = 1
PARALLEL_MIN_TREATMENT_GROUPS = 2
REPLICATE_MIN_PERIODS = 3
REPLICATE_2X2X4_TYPICAL_PERIODS = 4
REPLICATE_2X2X4_TYPICAL_SEQUENCE_COUNT = 2

# Decision / recommendation confidence bands (not PK math)
CONFIDENCE_GUIDELINE = 0.9
CONFIDENCE_EXPERT_OVERRIDE = 0.95
CONFIDENCE_HEURISTIC = 0.55
CONFIDENCE_INSUFFICIENT = None

DESIGN_TYPES = (
    "CROSSOVER_2X2",
    "REPLICATE_2X2X4",
    "PARALLEL",
    "ADAPTIVE",
    "CUSTOM",
)

FOOD_CONDITIONS = ("FASTING", "FED", "FASTING_AND_FED", "UNKNOWN")
MEAL_TYPES = ("HIGH_CALORIE", "STANDARD", "LOW_CALORIE", "CUSTOM")
ELIGIBILITY_CATEGORIES = ("inclusion", "non_inclusion", "exclusion")
DECISION_STATUSES = ("PROPOSED", "NEEDS_REVIEW", "VERIFIED", "REJECTED")
