"""Phase 12A.1 — expert knowledge / decision enums and constants.

No medical thresholds. All interview-derived seeds are PROPOSED.
"""

from __future__ import annotations

KNOWLEDGE_RULE_DOMAINS = (
    "INPUT",
    "REFERENCE_SELECTION",
    "DESIGN",
    "FOOD",
    "SAMPLE_SIZE",
    "SAMPLING",
    "WASHOUT",
    "ANALYTE",
    "PK",
    "ELIGIBILITY",
    "SAFETY",
    "STATISTICS",
    "SOURCE",
    "PREVIOUS_PROTOCOL",
    "QA",
)

KNOWLEDGE_RULE_STATUSES = ("PROPOSED", "VERIFIED", "UNVERIFIED", "REJECTED")

EXPERT_DECISION_TYPES = (
    "DESIGN",
    "REFERENCE_PRODUCT",
    "FOOD_CONDITION",
    "WASHOUT",
    "SAMPLING_PLAN",
    "ANALYTE_SELECTION",
    "PK_PARAMETER_SET",
    "ELIGIBILITY",
    "SAMPLE_SIZE",
    "STATISTICS",
    "SAFETY",
    "PROTOCOL_TEXT_EXCEPTION",
    "OTHER",
)

EXPERT_DECISION_STATUSES = ("PROPOSED", "APPROVED", "REJECTED", "SUPERSEDED")

KNOWLEDGE_GAP_IMPORTANCE = ("LOW", "MEDIUM", "HIGH", "CRITICAL")
KNOWLEDGE_GAP_STATUSES = ("OPEN", "RESOLVED", "DISMISSED")

REGULATORY_BASIS_STATUSES = ("PROPOSED", "VERIFIED", "UNVERIFIED", "REJECTED")

AUC_METRIC_TYPES = (
    "AUC_0_LAST",
    "AUC_0_72H",
    "AUC_0_INF",
    "AUC_0_LAST_OVER_INF",
    "AUC_0_72H_OVER_INF",
)

PK_PROFILE_KINDS = ("STANDARD_PROPOSED", "STUDY_SPECIFIC", "CUSTOM")

DIFF_TYPES = (
    "VALUE_CHANGED",
    "VALUE_UNCHANGED",
    "VALUE_REMOVED",
    "VALUE_ADDED",
    "LEGACY_SUSPECTED",
    "STRUCTURE_CHANGED",
    "TEXT_CHANGED",
)

DIFF_RISK_LEVELS = ("LOW", "MEDIUM", "HIGH", "CRITICAL")

QA_SEVERITIES = ("INFO", "WARNING", "ERROR", "CRITICAL")

QA_CATEGORIES = (
    "IDENTITY",
    "DESIGN",
    "FOOD",
    "SUBJECTS",
    "SAMPLING",
    "WASHOUT",
    "ANALYTE",
    "PK",
    "ELIGIBILITY",
    "SAFETY",
    "STATISTICS",
    "REFERENCES",
    "SCHEDULE",
    "LEGACY",
    "DOCUMENT",
)

KNOWLEDGE_FOUNDATION_VERSION = "KNOWLEDGE.FOUNDATION.v1"
