"""Organization and person role constants for protocol administration."""

from __future__ import annotations

# Organization roles
ORG_SPONSOR = "SPONSOR"
ORG_CLINICAL_CENTER = "CLINICAL_CENTER"
ORG_CLINICAL_SITE = "CLINICAL_SITE"
ORG_BIOANALYTICAL_LAB = "BIOANALYTICAL_LAB"
ORG_ANALYTICAL_LAB = "ANALYTICAL_LAB"
ORG_LABORATORY = "LABORATORY"
ORG_CRO = "CRO"
ORG_PHARMACY = "PHARMACY"
ORG_INSURANCE = "INSURANCE"
ORG_FINANCING = "FINANCING"
ORG_KEY = "KEY"
ORG_OTHER = "OTHER"

CLINICAL_CENTER_ROLES = frozenset({ORG_CLINICAL_CENTER, ORG_CLINICAL_SITE})
INVESTIGATOR_ORG_ROLES = frozenset({"INVESTIGATOR", "PRINCIPAL_INVESTIGATOR"})
LAB_ROLES = frozenset({ORG_BIOANALYTICAL_LAB, ORG_ANALYTICAL_LAB, ORG_LABORATORY})
KEY_ORG_ROLES = frozenset({ORG_CRO, ORG_PHARMACY, ORG_KEY, "MONITORING", "DATA_MANAGEMENT"})
SPONSOR_PERSON_ROLES = frozenset(
    {
        "SPONSOR_AUTHORIZED",
        "SPONSOR_PERSON",
        "AUTHORIZED_PERSON",
        "SPONSOR_SIGNATORY",
    }
)
MEDICAL_EXPERT_ROLES = frozenset({"MEDICAL_EXPERT"})
INVESTIGATOR_PERSON_ROLES = frozenset({"INVESTIGATOR", "PRINCIPAL_INVESTIGATOR"})
SIGNATORY_PERSON_ROLES = frozenset({"SPONSOR_SIGNATORY", "SPONSOR_AUTHORIZED", "PRINCIPAL_INVESTIGATOR", "INVESTIGATOR"})
